# Use official Python image
FROM python:3.8.0

# Install system dependencies
RUN apt-get update && apt-get install -y libsndfile1

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY . .

# Command to run Celery worker
CMD ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]
