version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8000:8000"
    environment:
      - BROKER_URL=redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
      - RESULT_BACKEND=redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: myapp-worker
    depends_on:
      - app
    environment:
      - BROKER_URL=redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
      - RESULT_BACKEND=redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
    restart: always
