services:
  - name: VerifyNG
    type: web
    runtime: docker
    repo: https://github.com/Oluwateezzy/verifyNg
    envVars:
      - key: BROKER_URL
        value: redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
      - key: RESULT_BACKEND
        value: redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /docs
    autoDeploy: true

  - name: verifyNg-worker
    type: worker
    runtime: docker
    repo: https://github.com/Oluwateezzy/verifyNg
    envVars:
      - key: BROKER_URL
        value: redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
      - key: RESULT_BACKEND
        value: redis://default:LP1uVzR2tbS0DK80j6kpvS1iDBt4qFDX@redis-10493.c270.us-east-1-3.ec2.redns.redis-cloud.com:10493
    plan: free
    env: docker
    dockerfilePath: Dockerfile.worker
    startCommand: "celery -A app.worker.celery_app worker --loglevel=info"
    autoDeploy: true
